### ISSUE TITLE
Reduce module load time

### ISSUE THREAD

**Issue by vjpr** [shutterstock/node-common-errors#20]
It takes quite a long time to load this module at present.

```
npm install -g require-time
npm init
npm install common-errors
require-time common-errors
206ms	common-errors
```

- There are a lot of files. Maybe bundling the app into a single file would help.
- Lodash is pegged to an exact version. Use a semver range instead.

**Comment by dfenster** [comment]
Hi there, 

Thanks for reporting this. 
I tried using require-time on my machine and got around 70ms.
I then commented out everything except lodash and got roughly the same time.
I then commented out lodash and got 2ms.

I think I'll just not use lodash if it's that bad. I don't really need it. 

I don't rely on semver for my dependencies because I don't trust that modules will adhere to semver rules. I don't want the package to spontaneously break in the future because a dependency made a bad decision.

**Comment by dfenster** [comment]
I uploaded a new version that should be faster. The remaining time is likely from require('http') inside HttpStatusError to get status codes. If there's still trouble, I'll copy/paste them.

**Comment by vjpr** [comment]
Awesome thanks!

Its down to a nice 40ms for me :)

**Comment by vjpr** [comment]
This is what it looks like for `NotFoundError`.

```
  26ms ../dev-live/drum/node_modules/common-errors/index.js
    14ms ../dev-live/drum/node_modules/common-errors/lib/middleware/errorHandler.js
      14ms ../dev-live/drum/node_modules/common-errors/lib/http-status.js
    1ms ../dev-live/drum/node_modules/common-errors/lib/helpers/class-generator.js
    1ms ../dev-live/drum/node_modules/common-errors/lib/alreadyInUse.js
    1ms ../dev-live/drum/node_modules/common-errors/lib/argument.js
    1ms ../dev-live/drum/node_modules/common-errors/lib/authenticationRequired.js
    1ms ../dev-live/drum/node_modules/common-errors/lib/notPermitted.js
    1ms ../dev-live/drum/node_modules/common-errors/lib/validation.js
```
